[package]
name = "rust_abf"
version = "0.4.4"
edition = "2021"
rust-version = "1.66"
license = "MIT"
authors = ["Luca Rossi <lucarossi147@gmail.com>"]
description = "Rust crate for reading data from Axon Binary Format (ABF) files."
repository = "https://github.com/lucarossi147/rust_abf"
homepage = "https://github.com/lucarossi147/rust_abf"
documentation = "https://docs.rs/rust_abf"
readme = "README.md"
keywords = ["abf", "electrophysiology", "axon", "patch-clamp", "neuroscience"]
categories = ["science", "parser-implementations", "encoding"]
exclude = ["tests/test_abf/*", "tests/golden/*", "scripts/*", ".github/*", "benches/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.9.5"

[dev-dependencies]
criterion = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.13.0"

[[bench]]
name = "read"
harness = false
